### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghutchis** [kleuter/qcocoamessagebox#1]
This looks like a nice approach! 

There isn't a license posted. Do you mind if I include it in a 3-clause BSD-licensed app? (https://avogadro.cc/)

I'm really annoyed that Qt hasn't managed to produce native message dialogs, despite repeated bug reports.

**Comment by kleuter** [comment]
Absolutely, I also plan to release qcocoacontrols which has lots of native macOS controls to be used easy with Qt

**Comment by kleuter** [comment]
Added the MIT license

**Comment by kleuter** [comment]
qcocoamessagebox is now a part of
https://github.com/crystalidea/qcocoacontrols

**Comment by ghutchis** [comment]
Thank you - this is a great help!
